### ISSUE TITLE
just a question - kafka 0.8.1.1

### ISSUE THREAD

**Issue by foovungle** [stealthly/scala-kafka#28]
This is not an issue per se. I see that you've started development for kafka 0.8.2.x. If I wanted to use this for kafka 0.8.1.1, which commit of this project should I use? Thanks!

**Comment by joestein** [comment]
I would recommend using master and using the 0.8.2.1 client which works fine with 0.8.1.1 brokers. You can change the broker in the vagrant file to be 0.8.1.1 here https://github.com/stealthly/scala-kafka/blob/master/vagrant/kafka.sh#L35 and it should work without issue. If you really need to use the 0.8.1.1 client library also then checkout the 0.8.1.1 branch https://github.com/stealthly/scala-kafka/tree/0.8.1.1 which has the last commit after the 0.8.1.1 release.

**Comment by foovungle** [comment]
Thanks for the quick response. Will try this next week.

**Comment by foovungle** [comment]
Ended up using
    "ly.stealth" % "scala-kafka" % "0.1.0.0"
in my libraryDependecies & seems to be working ok
